# Generated by Django 5.2.17 on 2026-10-06 10:11

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=60)),
                ('body', models.TextField(help_text='Markdown-ish plain text. Paragraphs are separated by blank lines.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='helpcenter.article')),
            ],
            options={
                'ordering': ['article', 'position'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
