# Generated by Django 5.2.17 on 2026-10-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chunk',
            name='chunk_embedding_hnsw',
        ),
    ]
