# Generated by Django 5.2.17 on 2026-10-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Services this vet performs.', related_name='vets', to='clinic.service'),
        ),
    ]
