# Generated by Django 5.2.17 on 2026-10-06 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('book', 'Book'), ('reschedule', 'Reschedule'), ('cancel', 'Cancel')], max_length=12)),
                ('payload', models.JSONField()),
                ('summary', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('result', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='assistant.conversation')),
            ],
        ),
    ]
