# Generated by Django 5.2.17 on 2026-10-06 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_evalrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='result',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
