# Generated by Django 5.2.17 on 2026-10-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_audit_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalrun',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
